import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./(component)/navbar";
import Logobar from "./(component)/logobar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <Logobar />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
